import type { Metadata } from "next"
import { Geist, Geist_Mono, Gantari } from "next/font/google"
import "./globals.css"
import { Header, Footer } from "@/components/layout"

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"]
})

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"]
})

const gantari = Gantari({
	variable: "--font-gantari",
	subsets: ["latin"]
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} ${gantari.variable} antialiased`}>
				<div className="">
					<Header />
					{children}
					<Footer />
				</div>
			</body>
		</html>
	)
}
